spring:
  application:
    name: base-service-api-gateway-admin
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db.host}:${db.port}/${db.database}?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF8
    username: ${db.username}
    password: ${db.password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 900000
      connection-timeout: 15000
      connection-test-query: SELECT 1
  thymeleaf:
    cache: false

server:
  port: 8085

management:
  server:
    servlet:
      context-path: /
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring.jackson.serialization.write_dates_as_timestamps: false
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  type-aliases-package: com.risen.base.api.gateway.storage.db.model
  mapper-locations: classpath*:/mapper/*.xml

