spring:
  application:
    name: base-service-api-gateway-server
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db.host}:${db.port}/${db.database}?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF8
    username: ${db.username}
    password: ${db.password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 900000
      connection-timeout: 15000
      connection-test-query: SELECT 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      app:
        skip: false
      server:
        skip: false


#      routes:
#        - id: middle-service-user-server
#          uri: lb://middle-service-user-server
#          predicates:
#            - Path=/user/**
#          filters:
#            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${eureka.defaultZone}

mybatis:
  type-aliases-package: com.risen.base.api.gateway.mapper
  mapper-locations: classpath*:/mapper/*.xml
