spring:
  application:
    name: base-service-api-gateway-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.26.21.27:3306/risen?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF8
    username: root
    password: 3ae560c8e28f6faf
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 900000
      connection-timeout: 15000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.risen.base.api.gateway.mapper
  mapper-locations: classpath*:/mapper/*.xml